VGG16:
  AUGMENTATION: True
  IMAGE_SIZE: [224,224,3] # as per vgg
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 55
  CLASSES: 100
  WEIGHTS: imagenet
  OPTIMIZER: Adam
  LEARNING_RATE: 0.001
  DROPOUT_RATE: 0.2


INCEPTIONV3:
  AUGMENTATION: True
  IMAGE_SIZE: [224,224,3]
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 3
  CLASSES: 100
  WEIGHTS: imagenet
  OPTIMIZER: Adam
  LEARNING_RATE: 0.001
  DROPOUT_RATE: 0.2


EFFICIENTNETB6:
  AUGMENTATION: True
  IMAGE_SIZE: [528,528,3]
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 55
  CLASSES: 100
  WEIGHTS: imagenet
  OPTIMIZER: Adam
  LEARNING_RATE: 0.001
  DROPOUT_RATE: 0.2