artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source_url: https://www.kaggle.com/datasets/gpiosenka/sports-classification
  # source_url: https://www.kaggle.com/datasets/gpiosenka/headgear-image-classification
  # source_url: https://www.kaggle.com/datasets/gpiosenka/100-bird-species
  # source_url: https://www.kaggle.com/datasets/pavansanagapati/images-dataset
  # source_url: https://www.kaggle.com/datasets/gpiosenka/balls-image-classification
  local_data_file: artifacts/data


base_model:
  root_dir: artifacts/base_model
  model_name: VGG16 # UPPER CASE NAME OF THE MODEL to extract model parameter form params.yaml
  base_model_path: artifacts/base_model/base_model.keras  # this is the path of the pretrained model loaded from the tf-keras
  updated_base_model_path: artifacts/base_model/pretrained_model.keras # this is the customized model based on dataset classes



model_training:
  model_name: VGG16 # UPPER CASE NAME OF THE MODEL to extract model parameter form params.yaml
  root_dir: artifacts/training
  model_path: artifacts/base_model/pretrained_model.keras
  trained_model_path: artifacts/training/trained_model.keras

  data_processing:
    dataset_path: artifacts/data/sports-classification/test
    batch_size: 16
    seed: 42
    rescale: 1./255
    shear_range: 0.2
    zoom_range: 0.2
    width_shift_range: 0.2
    height_shift_range: 0.2
    horizontal_flip: True
    validation_split: 0.2
    fill_mode: nearest